---
- name: Install fail2ban package
  apt:
    pkg: fail2ban
    state: present

- name: Enable fail2ban
  service:
    name: fail2ban
    enabled: yes

- name: Copy jail.conf to jail.local
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Setup Actions
  template:
    src: 'actions/{{ item }}.conf'
    dest: '/etc/fail2ban/action.d/{{ item }}.conf'
  with_items:
    - iptables-docker

- name: Setup Filters
  template:
    src: 'filters/{{ item }}.conf'
    dest: '/etc/fail2ban/filter.d/{{ item }}.conf'
  with_items:
    - nginx-proxy

- name: Setup Jails
  template:
    src: 'jails/{{ item }}.conf'
    dest: '/etc/fail2ban/jail.d/{{ item }}.conf'
  with_items:
    - nginx-proxy

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
