os: linux
dist: bionic
language: python
python: 3.7

addons:
  hosts:
    - test_site
  mariadb: 10.3

services:
  - mysql

git:
  depth: 1

cache:
  pip: true
  directories:
    - backbone/packer/images
    - backbone/packer/builds

jobs:
  include:
    - name: Backbone Base Image Build
      if: commit_message =~ travis:rebuild-image
      before_script:
        - sudo rm /usr/local/bin/packer
        - python3 $TRAVIS_BUILD_DIR/backbone/setup.py
      script:
        - sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor build'
        - sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor up'
        - sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor ssh -c "echo Hello, World"'
      install:
        - pip install -e $TRAVIS_BUILD_DIR
        - mkdir ~/scratch && cd ~/scratch

    - name: Backbone Tests
      script: backbone tests
      install:
        - pip install -e $TRAVIS_BUILD_DIR
        - mkdir ~/scratch && cd ~/scratch

    - name: Press Tests
      python: 3.7
      env: DB=mariadb TYPE=server
      script:
        - bench --site test_site run-tests --app press --coverage
        - flake8 --ignore W191,E501,W503 apps/press/press
        - black --check apps/press/press

      install:
        - cd ~
        - source ./.nvm/nvm.sh
        - nvm install 12

        - pip install frappe-bench flake8 git+https://github.com/adityahase/black

        - bench init frappe-bench --skip-assets --python $(which python)

        - mkdir ~/frappe-bench/sites/test_site
        - cp $TRAVIS_BUILD_DIR/.travis/$DB.json ~/frappe-bench/sites/test_site/site_config.json

        - if [ $DB == "mariadb" ];then
          mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'";
          mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'";

          mysql -u root -e "DROP DATABASE IF EXISTS test_frappe";
          mysql -u root -e "CREATE DATABASE test_frappe";
          mysql -u root -e "CREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe'";
          mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost'";

          mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'";
          mysql -u root -e "FLUSH PRIVILEGES";
          fi

        - cd ./frappe-bench

        - sed -i 's/watch:/# watch:/g' Procfile
        - sed -i 's/schedule:/# schedule:/g' Procfile

        - if [ $TYPE == "server" ]; then sed -i 's/socketio:/# socketio:/g' Procfile; fi
        - if [ $TYPE == "server" ]; then sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile; fi

        - bench get-app press $TRAVIS_BUILD_DIR
        - bench start &
        - bench --site test_site reinstall --yes

      after_script:
        - pip install coverage==4.5.4
        - pip install python-coveralls
        - coveralls -b apps/press -d ../../sites/.coverage
