---
- name: Create shared directory
  file:
    path: "{{ shared_directory }}"
    state: directory
    owner: frappe
    group: frappe
    mode: '0755'


- name: Add NFS mount to Fstab
  mount:
    src: "{{ primary_server_private_ip }}:/home/frappe/benches"
    path: "{{ shared_directory }}"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,intr,_netdev
    state: mounted

