---
- name: Install NGINX
  apt:
    pkg:
      - nginx
      - nginx-extras
      - apache2-utils
    state: present

- name: Remove Default Enabled NGINX Virtual Host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove Default Available NGINX Virtual Host
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Restart NGINX and Enable at Boot
  service:
    name: nginx
    state: restarted
    enabled: yes
