---
- name: Move bench data to benches directory
  become: yes
  shell: mv /home/frappe/shared/* /home/frappe/benches/

- name: Remove shared directory after sync
  become: yes
  file:
    path: /home/frappe/shared
    state: absent


