---
- name: Move bench data to benches directory
  become: yes
  shell: mv "{{ shared_directory }}"/* /home/frappe/benches/

- name: Unmount shared volume
  become: yes
  mount:
    path: "{{ shared_directory }}"
    state: unmounted

  failed_when: false


- name: Remove shared volume from fstab
  become: yes
  mount:
    path: "{{ shared_directory }}"
    state: absent

  failed_when: false


- name: Remove shared directory after sync
  become: yes
  file:
    path: "{{ shared_directory }}"
    state: absent
