---
- name: Move bench data to benches directory
  become: yes
  shell: mv "{{ shared_directory }}"/* /home/frappe/benches/

- name: Remove shared directory after sync
  become: yes
  file:
    path: "{{ shared_directory }}"
    state: absent
