---
- name: Setup Registry Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: docker
    - role: registry
    - role: node_exporter
    - role: cadvisor
