---
- name: Setup Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: nat_iptables
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: mount
    - role: bench
    - role: docker
    - role: node_exporter
    - role: cadvisor
    - role: statsd_exporter
    - role: filebeat
    - role: clamav
    - role: gpg_config
    - role: aide
    - role: additional_process_hardening
    - role: warning_banners
    - role: auditd
    - role: sshd_hardening
    - role: pam
    - role: user_ssh_certificate
    - role: earlyoom_memory_limits
    - role: install_and_setup_ncdu
    - role: iptables
