---
- name: Prepare primary proxy for failover
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Stop lsyncd and disable
      systemd:
        name: lsyncd
        enabled: no
        state: stopped

    - name: Stop NGINX Reload Manager
      command: 'sudo supervisorctl stop agent:nginx_reload_manager'
      args:
        chdir: /home/frappe/agent
