---
- name: Create parent directory
  become: yes
  file:
    path: "{{ parent_mountpoint }}"
    state: directory
    owner: frappe
    group: frappe
    mode: '0755'

- name: Add shared volume mount to fstab and mount it
  become: yes
  mount:
    src: "{{ parent_mountpoint }}"
    path: "{{ shared_directory }}"
    fstype: none
    opts: bind,nofail
    state: mounted
