- name: Update APT Cache
  apt:
    update_cache: yes

- name: Update ClamAV and related packages so updating of virus definitions work
  apt:
    pkg:
      - clamav
      - clamav-base
    state:
      latest

- name: Update freshclam
  command: freshclam
  async: 3600
  poll: 5

- name: Scan home directory
  command: 'clamscan --max-filesize=100M --max-scansize=100M --infected --recursive=yes /home'
  async: 32000
  poll: 300
