---
- name: Remove Old Docker Packages
  apt:
    state: absent
    force: yes
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install Docker Dependencies
  apt:
    state: present
    force: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Docker Repository Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Add Frappe User to docker Group
  user:
    name: frappe
    groups:
      - docker
    append: true

- name: Setup Docker Metrics
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restart Docker Daemon
  systemd:
    name: docker
    state: restarted

- name: Get Docker Info
  command: docker info

- name: Restart Agent processes
  supervisorctl:
    name: "agent:"
    state: restarted
